---
title: "ADS 506 Final"
author: "Lina Nguyen"
date: "11/28/2021"
output: pdf_document
---

### importing data
```{r}
fire <- read.csv('/Users/linanguyen/Desktop/Fire_clean.csv')
head(fire)
```

### view statistic summary of fire dataset
```{r}
summary(fire)
```

### counting number of occurences
```{r}
lapply(fire, table)

```

### check for missing values
```{r}
colSums(is.na(fire))
```

### concatenate all entries by value in another column and add their counts 
## WRONG CODE
```{r}
problem_clean1 <- aggregate(problem_count~problem_clean,fire,length)
names(problem_clean1)[2] <- 'problem_clean1'

problem_count1 <- aggregate(problem_count~problem_clean,fire,sum)
names(problem_count1)[2] <- 'problem_count1'


merge(problem_clean1, problem_count1)
```



```{r}
library(ggplot2)
```
```{r}
ggplot(data = fire) + geom_bar(mapping = aes(x = year_response)) + ggtitle('Number of Incidences per Year') + xlab('Month') + ylab('Count') + scale_x_continuous(breaks = scales::pretty_breaks(n = 16)) 
```
```{r}
ggplot(data = fire) + geom_histogram(mapping = aes(x = month_response)) + scale_x_continuous(breaks = scales::pretty_breaks(n = 12)) + ggtitle('Number of Incidences per Month') + xlab('Month') + ylab('Count')

```
### subset data into years
```{r}
year <- split(fire, fire$year_response)
names <- c('y6', 'y7', 'y8', 'y9', 'y10', 'y11', 'y12', 'y13', 'y14', 'y15', 'y16', 'y17', 'y18', 'y19', 'y20', 'y21')

for (i in 1:length(year)) {
  assign(names[i], year[[i]])
}
```

### plotting individual years
```{r}
ggplot(data = y6) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2006') + xlab('Month') + ylab('Count')

ggplot(data = y7) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2007') + xlab('Month') + ylab('Count')

ggplot(data = y8) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2008') + xlab('Month') + ylab('Count')

ggplot(data = y9) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2009') + xlab('Month') + ylab('Count')

ggplot(data = y10) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2010') + xlab('Month') + ylab('Count')

ggplot(data = y11) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2011') + xlab('Month') + ylab('Count')

ggplot(data = y12) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2012') + xlab('Month') + ylab('Count')

ggplot(data = y13) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2013') + xlab('Month') + ylab('Count')

ggplot(data = y14) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2014') + xlab('Month') + ylab('Count')

ggplot(data = y15) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2015') + xlab('Month') + ylab('Count')

ggplot(data = y16) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2016') + xlab('Month') + ylab('Count')

ggplot(data = y17) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2017') + xlab('Month') + ylab('Count')

ggplot(data = y18) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2018') + xlab('Month') + ylab('Count')

ggplot(data = y19) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2019') + xlab('Month') + ylab('Count')

ggplot(data = y20) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2020') + xlab('Month') + ylab('Count')

ggplot(data = y21) + geom_bar(mapping = aes(x = problem)) + ggtitle('Number of Incidences 2021') + xlab('Month') + ylab('Count')



```

#checking to see number of unique values in problem
```{r}
unique <- unique(fire$problem)
```

### subset data into problem
```{r}
problem <- split(fire, fire$problem)
names1 <- c(unique)

for (i in 1:length(problem)) {
  assign(names1[i], problem[[i]])
}
```

```{r}
assign(names1, problem)
```

```{r}
active_shooter <- data.frame(`Active Shooter`)
ggplot(data = active_shooter) + geom_bar(mapping = aes(x = year_response)) + xlab('Year') + ylab('Count') + ggtitle('Calls for Active Shooters per Year') + scale_x_continuous(breaks = scales::pretty_breaks(n = 16)) 

ggplot(data = active_shooter) + geom_bar(mapping = aes(x = month_response)) + xlab('Month') + ylab('Count') + ggtitle('Calls for Active Shooters per Month') + scale_x_continuous(breaks = scales::pretty_breaks(n = 12)) 
```





